#' create_test_GGIRconfig
#'
#' @param configfile Config object
#' @param desiredtz desiredtz to be used inside config file
#' @return No object return only file created
#' @importFrom utils write.csv
#' @export

create_test_GGIRconfig = function(configfile=c(), desiredtz = "Europe/London") {
  config = structure(list(argument = c("GGIR_version", "R_version", "backup.cal.coef", 
                              "chunksize", "configtz", "dayborder", "do.anglex", "do.angley", 
                              "do.anglez", "do.bfen", "do.cal", "do.dev_roll_med_acc_x", "do.dev_roll_med_acc_y", 
                              "do.dev_roll_med_acc_z", "do.en", "do.enmo", "do.enmoa", "do.hfen", 
                              "do.hfenplus", "do.lfen", "do.lfenmo", "do.mad", "do.roll_med_acc_x", 
                              "do.roll_med_acc_y", "do.roll_med_acc_z", "dynrange", "hb", "lb", 
                              "minloadcrit", "n", "print.filename", "printsummary", "windowsizes", 
                              "acc.metric", "bout.metric", "config_file_in_outputdir", "datadir", 
                              "desiredtz", "do.parallel", "do.report", "f0", "f1", "GGIR_version", 
                              "i", "idloc", "isna", "minimumFileSizeMB", "mode", "outputdir", 
                              "overwrite", "R_version", "selectdaysfile", "storefolderstructure", 
                              "studyname", "tmp", "vecchar", "anglethreshold", "constrain2range", 
                              "ignorenonwear", "timethreshold", "colid", "coln1", "criterror", 
                              "def.noc.sleep", "do.visual", "excludefirstlast", "includenightcrit", 
                              "loglocation", "nnights", "outliers.only", "relyonsleeplog", 
                              "sleeplogidnum", "boutcriter.in", "boutcriter.lig", "boutcriter.mvpa", 
                              "boutdur.in", "boutdur.lig", "boutdur.mvpa", "excludefirstlast.part5", 
                              "save_ms5rawlevels", "threshold.lig", "threshold.mod", "threshold.vig", 
                              "timewindow", "boutcriter", "closedbout", "do.imp", "do.part3.pdf", 
                              "epochvalues2csv", "hrs.del.end", "hrs.del.start", "iglevels", 
                              "ilevels", "includedaycrit", "IVIS_epochsize_seconds", "IVIS_windowsize_minutes", 
                              "IVIS.activity.metric", "M5L5res", "maxdur", "mvpadur", "mvpathreshold", 
                              "ndayswindow", "qlevels", "qM5L5", "qwindow", "strategy", "TimeSegments2ZeroFile", 
                              "window.summary.size", "winhr", "dofirstpage", "viewingwindow", 
                              "visualreport"), value = c("Could not retrieve GGIR version", 
                                                         "R version 3.6.1 (2019-07-05)", "redo", "1", "c()", "0", "FALSE", 
                                                         "FALSE", "TRUE", "FALSE", "TRUE", "FALSE", "FALSE", "FALSE", 
                                                         "FALSE", "TRUE", "FALSE", "FALSE", "FALSE", "FALSE", "FALSE", 
                                                         "FALSE", "FALSE", "FALSE", "FALSE", "c()", "15", "0.5", "72", 
                                                         "4", "TRUE", "FALSE", "c(5,900,3600)", "ENMO", "1", "", "", desiredtz, 
                                                         "TRUE", "c(2,4,5)", "1", "5", "Could not retrieve GGIR version", 
                                                         "22", "2", "FALSE", "2", "c(1,2,3,4,5)", "", "TRUE", "R version 3.6.1 (2019-07-05)", 
                                                         "c()", "TRUE", "", "0", "c(MM,WW)", "5", "TRUE", "TRUE", "5", 
                                                         "", "", "3", "1", "FALSE", "FALSE", "16", "c()", "7", "FALSE", 
                                                         "FALSE", "TRUE", "0.9", "0.8", "0.8", "c(5,10,30)", "c(5,10)", 
                                                         "c(5,10)", "FALSE", "FALSE", "40", "100", "400", "c(MM,WW)", 
                                                         "0.8", "FALSE", "TRUE", "TRUE", "FALSE", "0", "0", "c()", "c()", 
                                                         "8", "30", "60", "1", "10", "7", "c(1,5,10)", "100", "7", "c()", 
                                                         "c()", "c(0,24)", "1", "c()", "10", "5", "FALSE", "1", "FALSE"
                              ), context = c(" not applicable", " not applicable", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "Calibration, Feature extraction, Epoch size, Time zone", "Calibration, Feature extraction, Epoch size, Time zone", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "General parameters", 
                                             "General parameters", "General parameters", "Parameters sleep detection", 
                                             "Parameters sleep detection", "Parameters sleep detection", "Parameters sleep detection", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters sleep period time detection with or wihout sleeplog", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Parameters time-use variables", "Parameters time-use variables", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Study design, Parameters descriptive analysis", 
                                             "Study design, Parameters descriptive analysis", "Visual report", 
                                             "Visual report", "Visual report")), class = "data.frame", row.names = c(NA, 
                                                                                                                     -112L))
  write.csv(x = config, file = configfile, row.names = FALSE)
}